### ISSUE TITLE
Restrict the file size from frontend  to 10 MB

### ISSUE THREAD

**Issue by chiraglulla** [Chirag-And-Dheeraj/video-streaming-server#21]

**Comment by chiraglulla** [comment]
@dheerajdlalwani what is to be done in this issue?
what are the high level checkpoints you have in your mind?

**Comment by chiraglulla** [comment]
@dheerajdlalwani
Restrict file size to 15 MB for one user in total? Or just one file to be <= 15 MB?

**Comment by dheerajdlalwani** [comment]
One file to be 15 MB
